server:
  port: 8082

spring:
  data:
    mongodb:
      host: 192.168.8.103
      port: 27017
      database: local

restClient:
  moviesInfoUrl: http://localhost:8080/v1/movieinfos
  reviewsUrl: http://localhost:8081/v1/reviews
